# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  app:
    build:
      args:
        VITE_TENANT_ID: ${VITE_TENANT_ID}
        VITE_CLIENT_ID: ${VITE_CLIENT_ID}
        BUILD_MODE: production  # Override to production build
    ports:
      - "8443:443"  # Production port for reverse proxy
    environment:
      - PYTHONPATH=/app
      - FRONTEND_PATH=/app/frontend/dist
      # Remove BASE_PATH since no sub-path needed
      - DB_PATH=/app/db_volume/favorites.db
      - CONFIG_PATH=/app/config_volume
      # Set timezone to match host system
      - TZ=Europe/Berlin
    volumes:
      # Override backup volume to use named volume in production (more secure)
      - backup_data:/app/backups
      # Keep all other volumes from base config
      - ssl_data:/app/ssl
      - ./.env:/app/.env:ro
      - ./Documents:/app/Documents:ro
      - vector_data:/app/vector_store
      - db_data:/app/db_volume
      - config_data:/app/config_volume
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:443/"]  # No sub-path
      interval: 30s
      timeout: 10s
      retries: 3

  # Keep the same init container - it's beneficial for production too
  init:
    build:
      args:
        VITE_TENANT_ID: ${VITE_TENANT_ID}
        VITE_CLIENT_ID: ${VITE_CLIENT_ID}
        BUILD_MODE: production

volumes:
  backup_data:
    driver: local
